// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project2

#ifndef _SQUARELINE_PROJECT2_UI_H
#define _SQUARELINE_PROJECT2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Chart1;
extern lv_obj_t *ui_StatusLabel;
void ui_event_ToggleButton( lv_event_t * e);
extern lv_obj_t *ui_ToggleButton;
extern lv_obj_t *ui_ToggleLabel;
void ui_event_ZoomButton( lv_event_t * e);
extern lv_obj_t *ui_ZoomButton;
void ui_event_ZoomLabel( lv_event_t * e);
extern lv_obj_t *ui_ZoomLabel;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
