// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project2

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_MainScreen,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_MainScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

ui_Container1 = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, lv_pct(100));
lv_obj_set_height( ui_Container1, lv_pct(100));
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );

ui_Chart1 = lv_chart_create(ui_Container1);
lv_obj_set_width( ui_Chart1, lv_pct(80));
lv_obj_set_height( ui_Chart1, lv_pct(88));
lv_obj_set_x( ui_Chart1, -1 );
lv_obj_set_y( ui_Chart1, 0 );
lv_obj_set_align( ui_Chart1, LV_ALIGN_TOP_RIGHT );
lv_chart_set_type( ui_Chart1, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_Chart1, 30);
lv_chart_set_range( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 3500);
lv_chart_set_div_line_count( ui_Chart1, 15, 20);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 5, 5, 10, 2, false, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 15, 2, true, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);

lv_obj_set_style_line_width(ui_Chart1, 1, LV_PART_ITEMS| LV_STATE_DEFAULT);

lv_obj_set_style_size(ui_Chart1, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_StatusLabel = lv_label_create(ui_Container1);
lv_obj_set_height( ui_StatusLabel, 20);
lv_obj_set_width( ui_StatusLabel, lv_pct(70));
lv_obj_set_align( ui_StatusLabel, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_long_mode(ui_StatusLabel,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_StatusLabel,"OK");
lv_obj_set_style_text_align(ui_StatusLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ToggleButton = lv_btn_create(ui_Container1);
lv_obj_set_width( ui_ToggleButton, 50);
lv_obj_set_height( ui_ToggleButton, 20);
lv_obj_set_align( ui_ToggleButton, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_flex_flow(ui_ToggleButton,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ToggleButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_ToggleButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ToggleButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ToggleButton, lv_color_hex(0x4F4F4F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ToggleButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ToggleLabel = lv_label_create(ui_ToggleButton);
lv_obj_set_width( ui_ToggleLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ToggleLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ToggleLabel, -131 );
lv_obj_set_y( ui_ToggleLabel, -146 );
lv_obj_set_align( ui_ToggleLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ToggleLabel,"Start");

ui_ZoomButton = lv_btn_create(ui_Container1);
lv_obj_set_width( ui_ZoomButton, 50);
lv_obj_set_height( ui_ZoomButton, 20);
lv_obj_set_x( ui_ZoomButton, -55 );
lv_obj_set_y( ui_ZoomButton, 0 );
lv_obj_set_align( ui_ZoomButton, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_flex_flow(ui_ZoomButton,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ZoomButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_ZoomButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ZoomButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ZoomButton, lv_color_hex(0x4F4F4F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ZoomButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ZoomLabel = lv_label_create(ui_ZoomButton);
lv_obj_set_width( ui_ZoomLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ZoomLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ZoomLabel, -131 );
lv_obj_set_y( ui_ZoomLabel, -146 );
lv_obj_set_align( ui_ZoomLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ZoomLabel,"Zoom");

lv_obj_add_event_cb(ui_ToggleButton, ui_event_ToggleButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ZoomLabel, ui_event_ZoomLabel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ZoomButton, ui_event_ZoomButton, LV_EVENT_ALL, NULL);

}
